# datasource
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
  datasource:
    url: jdbc:mysql://172.21.1.104:8066/acttest?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  activiti:
    check-process-definitions: false


logging:
  level:
    root: debug